In [2]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-55,  12,  91, -77, -44, -89])

In [4]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2, 3)
print(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, steps=15)
print(linspace)
linspace

tensor([ 3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000])


tensor([ 3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000])

In [10]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
tensor = torch.empty(2,3)
tensor.random_(0,10)
tensor

tensor([[8., 4., 5.],
        [9., 6., 8.]])

In [14]:
# Testing and comparing GPU and CPU

import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [15]:
start_time = time.time()

#Matrix operation
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0000000000


In [16]:
start_time = time.time()

#Matrix operation
zeros = torch.zeros(100,1000)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0109934807


In [17]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"GPU : {elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU : {elapsed_time:.8f}")

GPU : 0.13613319
CPU : 0.15337467


In [18]:
prob = torch.tensor([0.1,0.9])
samples = torch.multinomial(prob,num_samples=10, replacement=True)
samples

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [19]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [20]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.tril(torch.ones(5,5))==0

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [22]:
t = torch.zeros(2,3,4)

In [23]:
o = t.transpose(0,2)

In [24]:
o.shape

torch.Size([4, 3, 2])

In [25]:
torch.tensor([10.,10.,10.])

tensor([10., 10., 10.])

In [26]:
import torch.nn as nn
sample = torch.tensor([10,10.,10.])
linear = nn.Linear(3,3,bias=False)
linear(sample)

tensor([ 4.8355, -1.6861, -4.0365], grad_fn=<SqueezeBackward4>)

In [27]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax = F.softmax(tensor1,dim=0)

softmax

tensor([0.0900, 0.2447, 0.6652])

In [28]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.0822,  0.1523, -0.4752,  0.1461,  0.6877,  0.2357],
        [ 0.1250, -2.1711,  0.6314, -0.7392, -0.1277, -0.5467],
        [ 0.0145, -1.5540,  0.0346, -0.8309,  0.2191,  1.4384],
        [ 2.0433, -0.9931,  0.8360, -1.1718, -0.2477,  1.1018]],
       grad_fn=<EmbeddingBackward0>)
